#!/usr/bin/env bash
set -euo pipefail
# shellcheck source=infra/lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log "Assembling $ROOT/.env.local from SSM + Secrets Manager"

ENDPOINT="$(ssm_get db_endpoint)"; SECRET_ARN="$(ssm_get db_secret_arn)"; DBN="$(ssm_get db_name)"
[ -z "$ENDPOINT" ] && die "DB not provisioned — run 03_aurora.sh first"

SECRET_JSON="$(aws secretsmanager get-secret-value --secret-id "$SECRET_ARN" --query SecretString --output text)"
DBUSER="$(node -pe 'JSON.parse(process.argv[1]).username' "$SECRET_JSON")"
DBPASS="$(node -pe 'JSON.parse(process.argv[1]).password' "$SECRET_JSON")"
DBPASS_ENC="$(node -pe 'encodeURIComponent(process.argv[1])' "$DBPASS")"

POOL_ID="$(ssm_get cognito_user_pool_id)"
CLIENT_ID="$(ssm_get cognito_client_id)"
CLIENT_SECRET="$(ssm_get cognito_client_secret)"
BUCKET="$(ssm_get s3_media_bucket)"

ENVFILE="$ROOT/.env.local"
cat > "$ENVFILE" <<EOF
# Generated by infra/write_env.sh — CONTAINS SECRETS. Git-ignored; never commit.
DATABASE_URL=postgres://$DBUSER:$DBPASS_ENC@$ENDPOINT:5432/$DBN
AWS_REGION=$REGION
AWS_PROFILE=$AWS_PROFILE
APP_URL=http://localhost:3000
COGNITO_USER_POOL_ID=$POOL_ID
COGNITO_CLIENT_ID=$CLIENT_ID
COGNITO_CLIENT_SECRET=$CLIENT_SECRET
S3_MEDIA_BUCKET=$BUCKET
EOF
chmod 600 "$ENVFILE"

ok "Wrote $ENVFILE"
warn "Holds the DB password + Cognito secret. It is git-ignored — never commit it."
log  "Next: npm run db:migrate && npm run db:seed && npm run dev"
