/**
 * Applies schema migrations (generated by `npm run db:generate`) and then the
 * hand-written, idempotent RLS policies in db/policies.sql.
 *
 * Runs as the connecting (master) role, which bypasses RLS — exactly what we
 * want for DDL. Usage: `npm run db:migrate`
 */
import "dotenv/config";
import { readFileSync } from "node:fs";
import path from "node:path";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is required to run migrations");

  const pool = new Pool({
    connectionString: url,
    ssl: process.env.PGSSL === "disable" ? false : { rejectUnauthorized: false },
  });

  try {
    const db = drizzle(pool);
    console.log("→ Applying schema migrations from db/migrations …");
    await migrate(db, { migrationsFolder: "db/migrations" });

    console.log("→ Applying RLS policies from db/policies.sql …");
    const policies = readFileSync(path.join(process.cwd(), "db", "policies.sql"), "utf8");
    await pool.query(policies);

    console.log("✓ Migrations + RLS policies applied.");
  } finally {
    await pool.end();
  }
}

main().catch((err) => {
  console.error("✗ Migration failed:", err);
  process.exit(1);
});
